name: repository
description: "A new Flutter module project."

version: 1.0.0+1

environment:
  sdk: '>=3.2.0-131.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  network:
    path: ../network

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  module:
    androidX: true
    androidPackage: com.example.repository
    iosBundleIdentifier: com.example.repository
